export type MockExerciseTarget =
  | { type: "duration"; seconds: number }
  | { type: "reps"; reps: number };

export type MockExercise = {
  id: string;
  title: string;
  description: string;
  help: string;
  target: MockExerciseTarget;
};

export type MockWorkoutDifficulty = "Beginner" | "Intermediate" | "Advanced";
export const MOCK_WORKOUT_DIFFICULTIES: MockWorkoutDifficulty[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
];

export type MockWorkoutCategory =
  | "Fundamentals"
  | "Striking"
  | "Defense"
  | "Conditioning"
  | "Footwork"
  | "Strength";
export const MOCK_WORKOUT_CATEGORIES: MockWorkoutCategory[] = [
  "Fundamentals",
  "Striking",
  "Defense",
  "Conditioning",
  "Footwork",
  "Strength",
];

export type MockWorkout = {
  id: string;
  title: string;
  description: string;
  difficulty: MockWorkoutDifficulty;
  category: MockWorkoutCategory;
  totalDurationMinutes: number;
  restSecondsBetweenExercises: number;
  exercises: MockExercise[];
  lastDoneDate?: string;
};

export const mockWorkouts: MockWorkout[] = [
  {
    id: "workout-001",
    title: "Muay Thai Fundamentals",
    description: "Build a clean base with stance, jab-cross rhythm, teep timing, and low kick mechanics.",
    difficulty: "Beginner",
    category: "Fundamentals",
    totalDurationMinutes: 35,
    restSecondsBetweenExercises: 30,
    exercises: [
      {
        id: "exercise-001",
        title: "Stance and Guard Hold",
        description: "Set your stance, keep elbows tight, and stay balanced.",
        help: "Keep your chin tucked and weight centered over both feet.",
        target: { type: "duration", seconds: 60 },
      },
      {
        id: "exercise-002",
        title: "Jab-Cross Flow",
        description: "Throw relaxed jab-cross combinations with full recoil.",
        help: "Reset your guard after every cross before the next rep.",
        target: { type: "reps", reps: 24 },
      },
      {
        id: "exercise-003",
        title: "Rear Teep Control",
        description: "Practice balance, chamber, and straight-line extension.",
        help: "Drive the hips forward and return the foot under control.",
        target: { type: "reps", reps: 16 },
      },
    ],
  },
  {
    id: "workout-002",
    title: "Boxing Basics",
    description: "Sharpen hand combinations, guard recovery, and simple angle exits.",
    difficulty: "Beginner",
    category: "Striking",
    totalDurationMinutes: 28,
    restSecondsBetweenExercises: 25,
    exercises: [
      {
        id: "exercise-004",
        title: "Slip and Return",
        description: "Move your head off the center line and answer with a jab.",
        help: "Keep the slip small so you stay ready to punch back.",
        target: { type: "duration", seconds: 45 },
      },
      {
        id: "exercise-005",
        title: "One-Two Pivot",
        description: "Punch then pivot off to create a better angle.",
        help: "Turn on the lead foot and keep your base underneath you.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-006",
        title: "Lead Hook Mechanics",
        description: "Work on elbow alignment and hip rotation for the hook.",
        help: "Do not let the elbow drop below the line of the fist.",
        target: { type: "reps", reps: 18 },
      },
    ],
  },
  {
    id: "workout-003",
    title: "Low Kick Flow",
    description: "Link punch entries into low kicks with balance and clean recovery.",
    difficulty: "Intermediate",
    category: "Footwork",
    totalDurationMinutes: 32,
    restSecondsBetweenExercises: 35,
    exercises: [
      {
        id: "exercise-007",
        title: "Step-In Cross",
        description: "Enter range with a committed cross while staying balanced.",
        help: "Land the lead foot first so the rear side can drive through.",
        target: { type: "reps", reps: 16 },
      },
      {
        id: "exercise-008",
        title: "Cross to Low Kick",
        description: "Throw a rear cross and follow immediately with a low kick.",
        help: "Let the punch rotate your hips into the kick rather than forcing it.",
        target: { type: "reps", reps: 14 },
      },
      {
        id: "exercise-009",
        title: "Kick Recovery Check",
        description: "Reset stance quickly after the kick and be ready to defend.",
        help: "Bring the kicking leg back sharply and re-establish your guard.",
        target: { type: "duration", seconds: 50 },
      },
    ],
  },
  {
    id: "workout-004",
    title: "Defense Basics",
    description: "Train shell defense, checking kicks, and simple counters from safe positions.",
    difficulty: "Intermediate",
    category: "Defense",
    totalDurationMinutes: 30,
    restSecondsBetweenExercises: 30,
    exercises: [
      {
        id: "exercise-010",
        title: "High Shell Reset",
        description: "Cover safely against straight punches and return to stance.",
        help: "Keep the elbows connected to the ribs while you absorb impact.",
        target: { type: "duration", seconds: 45 },
      },
      {
        id: "exercise-011",
        title: "Lead Leg Check",
        description: "Raise the shin to check and land back in stance cleanly.",
        help: "Turn the knee outward and keep the supporting foot planted.",
        target: { type: "reps", reps: 18 },
      },
      {
        id: "exercise-012",
        title: "Check to Cross Counter",
        description: "Defend the kick and answer back with a straight punch.",
        help: "Counter only after your base is stable again.",
        target: { type: "reps", reps: 14 },
      },
    ],
  },
  {
    id: "workout-005",
    title: "Beginner Boxing Fundamentals",
    description: "Build basic punching mechanics and coordination.",
    difficulty: "Beginner",
    category: "Fundamentals",
    totalDurationMinutes: 21,
    restSecondsBetweenExercises: 30,
    exercises: [
      {
        id: "exercise-013",
        title: "Jab",
        description: "Lead-hand straight punches.",
        help: "Keep your rear hand protecting your chin.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-014",
        title: "Cross",
        description: "Rear-hand straight punches.",
        help: "Rotate your hips and shoulders.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-015",
        title: "Jab -> Cross",
        description: "Basic one-two combination.",
        help: "Snap the jab before firing the cross.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-016",
        title: "Lead Hook",
        description: "Lead-side hooks.",
        help: "Pivot the lead foot.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-017",
        title: "Rear Hook",
        description: "Rear-side hooks.",
        help: "Keep your elbow level with your fist.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-018",
        title: "Jab -> Jab -> Cross",
        description: "Pressure combination.",
        help: "Stay balanced throughout.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-006",
    title: "Core Kick Development",
    description: "Develop balance, timing and power in the main Muay Thai kicks.",
    difficulty: "Beginner",
    category: "Striking",
    totalDurationMinutes: 22,
    restSecondsBetweenExercises: 45,
    exercises: [
      {
        id: "exercise-019",
        title: "Lead Teep",
        description: "Lead-leg push kicks.",
        help: "Drive through the target.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-020",
        title: "Rear Teep",
        description: "Rear-leg push kicks.",
        help: "Use strong hip extension.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-021",
        title: "Low Kick",
        description: "Round kicks to the thigh.",
        help: "Strike with the shin.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-022",
        title: "Body Kick",
        description: "Round kicks to the body.",
        help: "Turn your hips over.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-023",
        title: "High Kick",
        description: "Head-level round kicks.",
        help: "Keep your guard up.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-024",
        title: "Switch Body Kick",
        description: "Body kick after a switch-step.",
        help: "Stay light on your feet.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-007",
    title: "Elbow Arsenal",
    description: "Develop cutting and close-range elbow attacks.",
    difficulty: "Intermediate",
    category: "Striking",
    totalDurationMinutes: 22,
    restSecondsBetweenExercises: 45,
    exercises: [
      {
        id: "exercise-025",
        title: "Horizontal Elbow",
        description: "Horizontal elbow strikes.",
        help: "Rotate through the target.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-026",
        title: "Upward Elbow",
        description: "Upward elbow strikes.",
        help: "Keep the motion compact.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-027",
        title: "Downward Elbow",
        description: "Downward chopping elbows.",
        help: "Strike sharply downward.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-028",
        title: "Diagonal Up Elbow",
        description: "Rising diagonal elbows.",
        help: "Step into range.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-029",
        title: "Diagonal Down Elbow",
        description: "Descending diagonal elbows.",
        help: "Stay balanced.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-030",
        title: "Spinning Elbow",
        description: "Rotational elbow strikes.",
        help: "Lead with the hips.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-008",
    title: "Knee Domination",
    description: "Build powerful and accurate knee strikes.",
    difficulty: "Intermediate",
    category: "Striking",
    totalDurationMinutes: 22,
    restSecondsBetweenExercises: 45,
    exercises: [
      {
        id: "exercise-031",
        title: "Straight Knee",
        description: "Direct forward knee strikes.",
        help: "Drive the hips through.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-032",
        title: "Long Knee",
        description: "Extended range knees.",
        help: "Cover distance efficiently.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-033",
        title: "Clinch Knee",
        description: "Knees from the clinch position.",
        help: "Control posture first.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-034",
        title: "Diagonal Knee",
        description: "Angled knee strikes.",
        help: "Target ribs and liver area.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-035",
        title: "Curved Knee",
        description: "Arcing knee strikes.",
        help: "Use hip rotation.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-036",
        title: "Jumping Knee",
        description: "Explosive airborne knees.",
        help: "Drive upward aggressively.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-009",
    title: "Defensive Foundation",
    description: "Master the core defensive tools of Muay Thai.",
    difficulty: "Beginner",
    category: "Defense",
    totalDurationMinutes: 21,
    restSecondsBetweenExercises: 30,
    exercises: [
      {
        id: "exercise-037",
        title: "High Guard",
        description: "Protect the head and chin.",
        help: "Keep elbows tight.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-038",
        title: "Long Guard",
        description: "Control range and attacks.",
        help: "Maintain structure.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-039",
        title: "Shin Check",
        description: "Defend incoming kicks.",
        help: "Raise the knee sharply.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-040",
        title: "Teep Parry",
        description: "Redirect incoming teeps.",
        help: "Use minimal movement.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-041",
        title: "Kick Catch",
        description: "Catch body kicks safely.",
        help: "Stay balanced.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-042",
        title: "Slip",
        description: "Move the head off-line.",
        help: "Keep movement compact.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-010",
    title: "Footwork Builder",
    description: "Improve movement, positioning and angles.",
    difficulty: "Beginner",
    category: "Footwork",
    totalDurationMinutes: 20,
    restSecondsBetweenExercises: 15,
    exercises: [
      {
        id: "exercise-043",
        title: "Step Back",
        description: "Create distance efficiently.",
        help: "Stay in stance.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-044",
        title: "Step Off-Line",
        description: "Move outside attack lines.",
        help: "Keep eyes forward.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-045",
        title: "Lateral Movement",
        description: "Move side-to-side.",
        help: "Stay light on your feet.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-046",
        title: "Circle Out",
        description: "Circle around an opponent.",
        help: "Maintain stance integrity.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-047",
        title: "Angle Step",
        description: "Create new attack angles.",
        help: "Pivot smoothly.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-048",
        title: "L-Step",
        description: "Retreat and angle out.",
        help: "Move decisively.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-011",
    title: "Advanced Boxing Chains",
    description: "Develop fluid punching combinations.",
    difficulty: "Advanced",
    category: "Striking",
    totalDurationMinutes: 23,
    restSecondsBetweenExercises: 60,
    exercises: [
      {
        id: "exercise-049",
        title: "Jab -> Cross",
        description: "Basic one-two.",
        help: "Snap every strike.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-050",
        title: "Jab -> Cross -> Lead Hook",
        description: "Three-punch combination.",
        help: "Rotate into the hook.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-051",
        title: "Cross -> Lead Hook -> Cross",
        description: "Power combination.",
        help: "Transfer weight efficiently.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-052",
        title: "Lead Uppercut -> Rear Uppercut -> Cross",
        description: "Uppercut chain.",
        help: "Drive from the legs.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-053",
        title: "Jab -> Jab -> Cross",
        description: "Pressure boxing.",
        help: "Maintain rhythm.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-054",
        title: "Lead Hook -> Rear Hook",
        description: "Alternating hooks.",
        help: "Stay balanced.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-012",
    title: "Counter Fighter",
    description: "Blend defensive actions with immediate counters.",
    difficulty: "Intermediate",
    category: "Defense",
    totalDurationMinutes: 22,
    restSecondsBetweenExercises: 45,
    exercises: [
      {
        id: "exercise-055",
        title: "Parry -> Jab",
        description: "Counter after a parry.",
        help: "Respond instantly.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-056",
        title: "Slip -> Cross",
        description: "Slip and counter.",
        help: "Stay compact.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-057",
        title: "Pull Counter",
        description: "Pull and return fire.",
        help: "Time the movement.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-058",
        title: "Check -> Return Kick",
        description: "Defend and retaliate.",
        help: "Kick immediately after the check.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-059",
        title: "Catch -> Sweep",
        description: "Off-balance the opponent.",
        help: "Control the leg securely.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-060",
        title: "Catch -> Knee",
        description: "Counter with a knee strike.",
        help: "Maintain posture.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
  {
    id: "workout-013",
    title: "Thai Conditioning Volume",
    description: "High-repetition striking endurance session.",
    difficulty: "Advanced",
    category: "Conditioning",
    totalDurationMinutes: 20,
    restSecondsBetweenExercises: 15,
    exercises: [
      {
        id: "exercise-061",
        title: "Jab",
        description: "Continuous jabs.",
        help: "Maintain pace.",
        target: { type: "reps", reps: 30 },
      },
      {
        id: "exercise-062",
        title: "Cross",
        description: "Continuous crosses.",
        help: "Rotate fully.",
        target: { type: "reps", reps: 30 },
      },
      {
        id: "exercise-063",
        title: "Low Kick",
        description: "Alternating low kicks.",
        help: "Stay balanced.",
        target: { type: "reps", reps: 30 },
      },
      {
        id: "exercise-064",
        title: "Body Kick",
        description: "Power body kicks.",
        help: "Turn your hips over.",
        target: { type: "reps", reps: 30 },
      },
      {
        id: "exercise-065",
        title: "Straight Knee",
        description: "Rapid knee strikes.",
        help: "Drive through the target.",
        target: { type: "reps", reps: 30 },
      },
      {
        id: "exercise-066",
        title: "Horizontal Elbow",
        description: "Continuous elbows.",
        help: "Stay compact.",
        target: { type: "reps", reps: 30 },
      },
    ],
  },
  {
    id: "workout-014",
    title: "Complete Thai Striker",
    description: "Balanced session covering all major Muay Thai skills.",
    difficulty: "Intermediate",
    category: "Fundamentals",
    totalDurationMinutes: 24,
    restSecondsBetweenExercises: 30,
    exercises: [
      {
        id: "exercise-067",
        title: "Jab -> Cross",
        description: "Fundamental boxing combination.",
        help: "Return to guard after each strike.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-068",
        title: "Body Kick",
        description: "Powerful round kick.",
        help: "Turn the hips.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-069",
        title: "Lead Teep",
        description: "Control distance.",
        help: "Push through the target.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-070",
        title: "Straight Knee",
        description: "Direct knee strikes.",
        help: "Use hip extension.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-071",
        title: "Horizontal Elbow",
        description: "Close-range elbow work.",
        help: "Rotate sharply.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-072",
        title: "Shin Check",
        description: "Defensive kick check.",
        help: "Raise the knee quickly.",
        target: { type: "reps", reps: 20 },
      },
      {
        id: "exercise-073",
        title: "Angle Step",
        description: "Create better positions.",
        help: "Stay balanced.",
        target: { type: "reps", reps: 20 },
      },
    ],
  },
];
